import type {Metadata} from "next";
// import {Inter} from "next/font/google";
import Image from "next/image";
import "./globals.css";
import StarsBackground from "@/src/StarsBackground";

// const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <StarsBackground/>
        {children}
        </body>
        </html>
    );
}
